### ISSUE TITLE
请问有双目的图像质量评估数据集吗？

### ISSUE THREAD

**Issue by Surrin1999** [SN-F-QR/DSN-IQA#1]
作者您好，我正在做双目图像的超像素分割的工作，打算用您的代码做一个application，但是似乎没有双目的图像质量评估数据集？

**Comment by SN-F-QR** [comment]
Sorry，这个方向我不了解

**Comment by Surrin1999** [comment]
> Sorry，这个方向我不了解

我找到了双目的图像质量评估数据集了，请问如果要使用其他的超像素分割模型来替换掉您文章里那个，是只需要修改spix_rim.py中的CNNRIM模型为我自己的模型就好了吗？

**Comment by Surrin1999** [comment]
请问能与您进一步探讨一下您这篇工作吗？具体内容已发送到您文章中给出的邮箱
